name: Remove tests

on:
  workflow_call:
    inputs:
      src:
        required: true
        type: string
      dst:
        required: true
        type: string
      commit_msg:
        type: string
        default: "chore: add notests file [skip ci]"

jobs:
  remove-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v5
      - name: Checkout code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Remove tests cases
        run: |
          mkdir -p "$(dirname ${{ inputs.dst }})"
          sed '/<tc:testCases/,/<\/tc:testCases>/Id' ${{ inputs.src }} > ${{ inputs.dst }}

      - name: Commit Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ inputs.dst }}

          if ! git diff --quiet --staged; then
            git commit -m "${{ inputs.commit_msg }}"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi
